#!/usr/bin/env bash

if ! type "zsh" > /dev/null; then
  . $DOTSPATH/lib/apt_install
  apt_install zsh autojump

  sudo chsh -s $(which zsh) $(whoami)
  sudo curl -sS https://starship.rs/install.sh | sh -s -- -y
fi

. $DOTSPATH/lib/link_file
link_dotfile .zshrc
link_dotfile .aliases
