#!/bin/bash
set -e

COMMAND=$1
DOTSPATH="$HOME/dotfiles"

if [ $XDG_SESSION_TYPE == "wayland" ]; then
  echo "This script is not compatible with Wayland: use X11 and restart the pc."
  echo ""
  echo "To change Wayland in favour of X11 run this:"
  echo "> sudo sed -i 's/#WaylandEnable=false/WaylandEnable=false/' /etc/gdm3/custom.conf && sudo reboot"
  exit 1
fi

if [ -e $DOTSPATH/.git ]; then
  cd $DOTSPATH && git pull
else
  git clone https://github.com/AlessioCoser/dotfiles-ubuntu.git $DOTSPATH
  cd $DOTSPATH
fi

function print_waiting_title {
  echo "------------------------------"
  echo $1
  echo "------------------------------"
  sleep 3
}

if [ -z ${COMMAND} ]; then
  COMMAND="all"
fi

if [ "$COMMAND" != "all" ] && [ "$COMMAND" != "scripts" ] && [ "$COMMAND" != "dots" ]; then
	echo "Usage: $0 [all, scripts, dots]"
  exit 1
fi

if [ "$COMMAND" == "all" ] || [ "$COMMAND" == "scripts" ]; then
  print_waiting_title "installing scripts"

  chmod +x scripts/*

  for file in $(echo scripts/*)
  do
    echo "--> executing $file"

    ./$file
  done
fi

if [ "$COMMAND" == "all" ] || [ "$COMMAND" == "dots" ]; then
  print_waiting_title "linking dot-files"

  for file in $(echo dots/.*)
  do
    if [ -f "$file" ]; then
      filename=$(basename "$file")

      echo "----> linking $filename"

      if [ -f ~/$filename.orig ]; then
        rm ~/$filename
      else
        if [ -f ~/$filename ]; then
          mv ~/$filename ~/$filename.orig
        fi
      fi

      ln -s ~/dotfiles/$file ~/$filename
    fi
  done
fi

echo ""
echo ""
echo "#########################################################"
echo "###############                           ###############"
echo "###############   INSTALLATION COMPLETE   ###############"
echo "###############                           ###############"
echo "###############     CLOSE THIS SHELL      ###############"
echo "###############     ----------------      ###############"
echo "#########################################################"
echo ""
echo ""