#!/usr/bin/env bash

. $DOTSPATH/lib/apt_install

# set keyboard blazingly fast
sudo kbdrate -r 1 -d 150 # only works on X11

mkdir -p ~/.local/bin
echo -e "\\nexport PATH=\"~/.local/bin:\$PATH\"\\n" >> ~/.bashrc
source ~/.bashrc

sudo apt update

apt_install net-tools wget htop tig

# install Monaco Font
mkdir -p ~/.fonts
curl -o ~/.fonts/Monaco-Linux.ttf "http://www.gringod.com/wp-upload/software/Fonts/Monaco_Linux.ttf"
sudo fc-cache -fv

wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraCode.zip
mkdir firacode && unzip -d firacode FiraCode.zip
mv firacode/FiraCode* ~/.fonts/
rm FiraCode.zip && rm -r firacode

# install gnome-shell extension installer
wget -O gnome-shell-extension-installer "https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer"
chmod +x gnome-shell-extension-installer
sudo mv gnome-shell-extension-installer /usr/bin/

# install shell extensions
gnome-shell-extension-installer --yes 779 # "clipboard-indicator@tudmotu.com"
gnome-shell-extension-installer --yes 906 # "sound-output-device-chooser@kgshank.net"

gnome-extensions enable sound-output-device-chooser@kgshank.net
gnome-extensions enable clipboard-indicator@tudmotu.com
dconf write "/org/gnome/shell/extensions/clipboard-indicator/cache-size" "2048"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/confirm-clear" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/disable-down-arrow" "true"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/display-mode" "0"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/enable-keybindings" "true"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/history-size" "99"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/move-item-first" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/notify-on-copy" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/preview-size" "99"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/refresh-interval" "500"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/strip-text" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/toggle-menu" "['<Control>Insert']"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/topbar-preview-size" "99"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/next-entry" "['<Control><Super>Right']"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/prev-entry" "['<Control><Super>Left']"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/clear-history" "['<Shift><Control>Delete']"

# configure bottom autohide dock
gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false
gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM
gsettings set org.gnome.shell.extensions.dash-to-dock show-mounts false
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
gsettings set org.gnome.shell.extensions.dash-to-dock autohide true
gsettings set org.gnome.shell.extensions.dash-to-dock intellihide true

# set light ubuntu color theme
gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-light'

# download and set wallpapers
# sudo curl -o /usr/share/backgrounds/starwars-orange.jpg https://i1.wp.com/wallpapercave.com/wp/wp11881623.jpg
# sudo curl -o /usr/share/backgrounds/starwars-yellow.jpg https://images.wallpapersden.com/image/download/r2-d2-star-wars-minimalist_a2xuaWWUmZqaraWkpJRqZWVlrWdqZWU.jpg
# sudo curl -o /usr/share/backgrounds/starwars-green.jpg https://images.wallpapersden.com/image/download/star-wars-skywalker-saga-minimal_a2xsbmqUmZqaraWkpJRnamtlrWZpaWU.jpg
sudo curl -o /usr/share/backgrounds/starwars-blue.jpg https://i1.wp.com/wallpapercave.com/wp/wp6722869.jpg

gsettings set org.gnome.desktop.screensaver picture-uri 'file:///usr/share/backgrounds/starwars-blue.jpg'
gsettings set com.ubuntu.login-screen background-picture-uri 'file:///usr/share/backgrounds/starwars-blue.jpg'
gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/starwars-blue.jpg'
