#!/usr/bin/env bash

. $DOTSPATH/lib/link_file
link_dotfile .bash_aliases
link_dotfile .inputrc
link_dotfile .colorprompt

if grep -Fxq "source ~/.colorprompt" ~/.bashrc
then
    echo "colorprompt already loaded. Skip."
else
    echo -e "\\nsource ~/.colorprompt\\n" >> .bashrc
    source ~/.bashrc
fi

if grep -Fxq "eval \"\$(zoxide init bash)\"" ~/.bashrc
then
  echo "zoxide already present. Skipping installation"
else
  curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
  echo -e "\\neval \"\$(zoxide init bash)\"\\n" >> ~/.bashrc
  source ~/.bashrc
fi
