#!/usr/bin/env bash

if ! type "docker" > /dev/null; then
  # reference: https://docs.docker.com/engine/install/ubuntu/
  . $DOTSPATH/lib/apt_install
  . $DOTSPATH/lib/apt_remove

  # remove all conflicting packages
  for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do apt_remove $pkg; done

  # Add the gpg certificate
  sudo apt update
  apt_install ca-certificates curl
  sudo install -m 0755 -d /etc/apt/keyrings
  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  sudo chmod a+r /etc/apt/keyrings/docker.asc

  # Add the repository to Apt sources:
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo apt update

  apt_install docker-ce docker-ce-cli containerd.io docker-compose-plugin

  sudo usermod -aG docker ${USER}
fi
