#!/usr/bin/env bash

if ! type "pyenv" > /dev/null; then
  . $DOTSPATH/lib/apt_install
  apt_install build-essential zlib1g-dev libbz2-dev libsqlite3-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev

  curl https://pyenv.run | bash

  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"

  eval "$(pyenv init --path)"
  pyenv install 3.11
  pyenv global 3.11
fi