#!/bin/bash

. $DOTSPATH/lib/execute_files
. $DOTSPATH/lib/print_title

execute_os_scripts() {
  local method="default"
  if [ "$1" == "custom" ]; then
    method="custom"
  fi

  if [[ $OSTYPE == 'darwin'* ]]; then

    execute_files $method $(echo $DOTSPATH/scripts/macos/*)
    print_title "INSTALLATION COMPLETE - CLOSE THIS TERMINAL"

  elif [[ $OSTYPE == 'linux'* ]]; then

    execute_files $method $(echo $DOTSPATH/scripts/ubuntu/*)
    print_title "INSTALLATION COMPLETE - CLOSE THIS TERMINAL"

  else
    print_title "INSTALLATION FAILED - OS NOT RECOGNIZED"
  fi
}
