#!/bin/bash
. $DOTSPATH/lib/print_title

execute_all_files() {
  for file in $@
  do
    print_title "EXECUTING $file"
    sudo chmod a+x $file
    $file
  done
}

execute_files() {
  local files=("$@")
  local all_files=${files[@]}
  local selected_indices=$(indices_of_array $all_files)
  ui_widget_select -l -m -s $selected_indices -i $all_files
  local select_response=${UI_WIDGET_RC[@]}
  local selected=()
  for index in $select_response
  do
    selected+=("${files[$index]}")
  done

  set -e

  execute_all_files ${selected[@]}
}
