#!/bin/bash
. $DOTSPATH/lib/print_title
. $DOTSPATH/lib/indices_of_array
. $DOTSPATH/lib/ui_widget_select

execute_all_files() {
  set -e

  for file in $@
  do
    print_title "EXECUTING $file"
    sudo chmod a+x $file
    $file
  done
}

execute_files() {
  local files=("$@")
  local all_files=${files[@]}

  execute_all_files ${all_files}

  # local selected_indices=$(indices_of_array $all_files)
  # ui_widget_select -l -m -s $selected_indices -i $all_files
  # local select_response=${UI_WIDGET_RC[@]}
  # local selected=()
  # for index in $select_response
  # do
  #   selected+=("${files[$index]}")
  # done

  # execute_all_files ${selected[@]}
}
