#!/bin/bash

. $DOTSPATH/lib/execute_files
. $DOTSPATH/lib/print_title

execute_os_scripts() {
  local method="default"
  if [ "$1" == "custom" ]; then
    method="custom"
  fi

  if [[ $OSTYPE == 'darwin'* ]]; then

    print_title "INSTALLATION STARTED - MacOS"
    execute_files $method $(echo $DOTSPATH/scripts/macos/*)
    print_title "INSTALLATION COMPLETE - CLOSE THIS TERMINAL"

  elif [[ $OSTYPE == 'linux'* ]]; then

    if grep -Fxq "ID=manjaro" /etc/os-release; then

      print_title "INSTALLATION STARTED - Manjaro"
      execute_files $method $(echo $DOTSPATH/scripts/arch/*)
      print_title "INSTALLATION COMPLETE - CLOSE THIS TERMINAL"

    elif grep -Fxq "ID=arch" /etc/os-release; then

      print_title "INSTALLATION STARTED - Arch Linux"
      execute_files $method $(echo $DOTSPATH/scripts/arch/*)
      print_title "INSTALLATION COMPLETE - CLOSE THIS TERMINAL"

    elif grep -Fxq "ID=ubuntu" /etc/os-release; then

      print_title "INSTALLATION STARTED - Ubuntu"
      execute_files $method $(echo $DOTSPATH/scripts/ubuntu/*)
      print_title "INSTALLATION COMPLETE - CLOSE THIS TERMINAL"

    else
      print_title "INSTALLATION FAILED - OS NOT RECOGNIZED"
    fi
  else
    print_title "INSTALLATION FAILED - OS NOT RECOGNIZED"
  fi
}
