#!/bin/bash

link_file() {
  local ORIGINAL_FILE=$1
  local DEST_FILE=$2
  local DEST_DIR="$(dirname "${DEST_FILE}")"

  mkdir -p $DEST_DIR
  if [ -f "$DEST_FILE" ]; then
    if [ -f "$DEST_FILE.orig" ]; then
      rm "$DEST_FILE"
    else
      mv "$DEST_FILE" "$DEST_FILE.orig"
    fi
  fi
  ln -s "$ORIGINAL_FILE" "$DEST_FILE"
}

link_dotfile() {
  local filename=$1

  link_file "$DOTSPATH/dots/$filename" "$HOME/$filename"
}
