#!/bin/bash

link_dotfile() {
  local dots_path=$1
  local file=$2
  if [ -f "$file" ]; then
    filename=$(basename "$file")

    echo "----> linking $filename"

    if [ -f ~/$filename.orig ]; then
      rm ~/$filename
    else
      if [ -f ~/$filename ]; then
        mv ~/$filename ~/$filename.orig
      fi
    fi

    ln -s $dots_path/$file ~/$filename
  fi
}
