#!/bin/bash

link_file() {
  local ORIGINAL_FILE=$1
  local DEST_FILE=$2

  mkdir -p "$(dirname "$DEST_FILE")"

  # backup only on first run if DEST is a real file (not a symlink)
  if [ -f "$DEST_FILE" ] && [ ! -L "$DEST_FILE" ] && [ ! -e "$DEST_FILE.orig" ]; then
    mv "$DEST_FILE" "$DEST_FILE.orig"
  fi

  ln -sfn "$ORIGINAL_FILE" "$DEST_FILE"
}

link_dotfile() {
  local filename=$1

  link_file "$DOTSPATH/dots/$filename" "$HOME/$filename"
}
