#!/usr/bin/env bash
set -e

# https://raw.githubusercontent.com/sindresorhus/mathiasbynens-dotfiles/master/.osx

###############################################################################
# Wallpaper                                                              #
###############################################################################
echo "WALLPAPER"
WALLPAPER="$HOME/Pictures/starwars-blue.jpg"
[ ! -f "$WALLPAPER" ] && curl -fsSLo "$WALLPAPER" 'https://i1.wp.com/wallpapercave.com/wp/wp6722869.jpg'
osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"$WALLPAPER\""

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################
echo "Keyboard input"
# Disable press-and-hold for keys in favor of key repeat
defaults write -g ApplePressAndHoldEnabled -bool false

# Set a blazingly fast keyboard repeat rate
defaults write -g KeyRepeat -int 1
defaults write -g InitialKeyRepeat -int 15

###############################################################################
# Screen                                                                      #
###############################################################################
echo "Screen and screenshot"
# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Save screenshots to the desktop
defaults write com.apple.screencapture location -string "${HOME}/Desktop"
# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"
# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

###############################################################################
# Finder                                                                      #
###############################################################################
echo "Finder"
# Set Desktop as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfDe"

# Finder: show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Empty Trash securely by default
defaults write com.apple.finder EmptyTrashSecurely -bool true

###############################################################################
# Dock, Dashboard, and hot corners                                            #
###############################################################################
echo "Dock, Dashboard, and hot corners"
# Set the icon size of Dock items to 42 pixels
defaults write com.apple.dock tilesize -int 42
# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true
# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-time-modifier -float 0
# Make Dock icons of hidden applications translucent
defaults write com.apple.dock showhidden -bool true
# Hide recent apps in the Dock
defaults write com.apple.dock show-recents -bool false

# Show indicator lights for open applications in the Dock
defaults write com.apple.dock show-process-indicators -bool true

# Speed up Mission Control animations
defaults write com.apple.dock expose-animation-duration -float 0

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

# Add iOS Simulator to Launchpad
SIM_LINK="/Applications/iPhone Simulator.app"
SIM_SRC="/Applications/Xcode.app/Contents/Applications/iPhone Simulator.app"
[ ! -L "$SIM_LINK" ] && [ -e "$SIM_SRC" ] && ln -s "$SIM_SRC" "$SIM_LINK" 2>/dev/null || true

killall Dock

###############################################################################
# Mac App Store                                                               #
###############################################################################
echo "Mac App Store"
# Enable the automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true
