#!/bin/bash

if ! type "brew" > /dev/null; then
  echo ".... brew install"
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
