#!/bin/bash
set -e
eval "$(/opt/homebrew/bin/brew shellenv)"

. $DOTSPATH/lib/brew_install
. $DOTSPATH/lib/link_file

brew install rectangle
brew install maccy

link_file "$DOTSPATH/.config/Rectangle/config.json" "$HOME/Library/Application Support/Rectangle/RectangleConfig.json"
