#!/bin/bash

brew install wget
brew install curl
brew install antigen
brew install autojump
brew install tig
brew install htop
brew install hub

if ! type "zsh" > /dev/null; then
  brew install zsh

  mkdir -p ~/.config
  ln -s /usr/local/share/antigen/antigen.zsh ~/.config/antigen.zsh

  chsh -s $(which zsh) $(whoami)
fi

. $DOTSPATH/lib/link_file
link_dotfile .zshrc
link_dotfile .aliases
