#!/bin/bash

. $DOTSPATH/lib/link_file

brew install --cask rectangle
brew install --cask maccy

sudo mkdir -p "/Users/$(whoami)/Library/Application\ Support/Rectangle"
sudo link_file "$DOTSPATH/.config/Rectangle/config.json" "/Users/$(whoami)/Library/Application Support/Rectangle/RectangleConfig.json"
