#!/bin/bash
set -e
eval "$(/opt/homebrew/bin/brew shellenv)"

. $DOTSPATH/lib/brew_install
. $DOTSPATH/lib/link_file

brew install zsh
brew install fzf
brew install zoxide
brew install starship
ZAP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/zap"
[ -d "$ZAP_DIR" ] || zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1 --keep

link_dotfile .zprofile
link_dotfile .zsh_aliases
link_dotfile .zshrc
link_file "$DOTSPATH/.config/starship.toml" "$HOME/.config/starship.toml"
