#!/bin/bash

. $DOTSPATH/lib/link_file
link_dotfile .bash_aliases
link_dotfile .inputrc
link_dotfile .colorprompt

brew install wget
brew install curl
brew install tig
brew install htop
brew install hub
brew install zoxide

if grep -Fxq "source ~/.colorprompt" ~/.bashrc
then
    echo "colorprompt already loaded. Skip."
else
    echo -e "\\nsource ~/.colorprompt\\n" >> .bashrc
    source ~/.bashrc
fi

if grep -Fxq "eval \"\$(zoxide init bash)\"" ~/.bashrc
then
  echo "zoxide already configured. Skipping configuration"
else
  echo -e "\\neval \"\$(zoxide init bash)\"\\n" >> .bashrc
  source ~/.bashrc
fi
