#!/bin/bash
eval "$(/opt/homebrew/bin/brew shellenv)"

if ! type "ghostty" > /dev/null; then
  brew install ghostty
fi

. $DOTSPATH/lib/link_file
link_file "$DOTSPATH/.config/ghostty/config" "$HOME/.config/ghostty/config"