#!/bin/bash
set -e
eval "$(/opt/homebrew/bin/brew shellenv)"

. $DOTSPATH/lib/brew_install
. $DOTSPATH/lib/link_file

brew install ghostty

link_file "$DOTSPATH/.config/ghostty/config" "$HOME/.config/ghostty/config"
