#!/usr/bin/env bash
set -e
eval "$(/opt/homebrew/bin/brew shellenv)"

brew install mise

. $DOTSPATH/lib/link_file
link_file "$DOTSPATH/.config/mise/config.toml" "$HOME/.config/mise/config.toml"

mise install
