#!/usr/bin/env bash
eval "$(/opt/homebrew/bin/brew shellenv)"

if ! type "mise" > /dev/null; then
  brew install mise

  . $DOTSPATH/lib/link_file
  link_file "$DOTSPATH/.config/mise/config.toml" "$HOME/.config/mise/config.toml"

  mise install
fi
