#!/usr/bin/env bash

if ! type "nvm" > /dev/null; then
  brew uninstall --ignore-dependencies node
  brew uninstall --force node
  brew install nvm
  mkdir ~/.nvm

  export NVM_DIR=~/.nvm
  source $(brew --prefix nvm)/nvm.sh

  nvm install 18.14.2
  nvm alias default 18.14.2
fi