#!/usr/bin/env bash

if ! type "sdk" > /dev/null; then
  curl -s "https://get.sdkman.io" | bash
  source "$HOME/.sdkman/bin/sdkman-init.sh"
  sdk install java 8.0.302-open
  sdk install java 18.0.1.1-open

  sdk default java 18.0.1.1-open
fi