#!/usr/bin/env bash


if ! type "pyenv" > /dev/null; then
  brew install pyenv

  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"

  eval "$(pyenv init --path)"
  pyenv install 3.10.6
  pyenv global 3.10.6

  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
fi