#!/usr/bin/env bash


if ! type "pyenv" > /dev/null; then
  brew install pyenv

  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"

  eval "$(pyenv init --path)"
  pyenv install 3.10.6
  pyenv global 3.10.6

  curl -sSL https://install.python-poetry.org | POETRY_HOME="$HOME/.poetry" python -
fi