#!/usr/bin/env bash
set -e
eval "$(/opt/homebrew/bin/brew shellenv)"

. $DOTSPATH/lib/brew_install
. $DOTSPATH/lib/link_file

if ! type "code" > /dev/null; then
  brew install visual-studio-code
  sleep 5
fi

# show extensions installed: `code --list-extensions`
code --install-extension akamud.vscode-theme-onelight
code --install-extension zhuangtongfa.material-theme
code --install-extension k--kato.intellij-idea-keybindings
# python
code --install-extension ms-python.python
code --install-extension ms-python.debugpy
code --install-extension ms-pyright.pyright
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension charliermarsh.ruff
# javascript
code --install-extension yoavbls.pretty-ts-errors
code --install-extension esbenp.prettier-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension vitest.explorer
# html and toml
code --install-extension mohd-akram.vscode-html-format
code --install-extension tamasfe.even-better-toml

link_file "$DOTSPATH/.config/Code/User/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
link_file "$DOTSPATH/.config/Code/User/keybindings.json" "$HOME/Library/Application Support/Code/User/keybindings.json"
