#!/usr/bin/env bash

# set keyboard blazingly fast
sudo kbdrate -r 1 -d 150

# add firacode font repository
sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"

sudo apt update

sudo apt install -y \
    net-tools \
    fonts-firacode \
    curl \
    wget \
    htop \
    vim \
    git \
    tig


# install Monaco Font
mkdir -p ~/.fonts
curl -o ~/.fonts/Monaco-Linux.ttf "http://www.gringod.com/wp-upload/software/Fonts/Monaco_Linux.ttf"
sudo fc-cache -fv


# install gnome-shell extension installer
wget -O gnome-shell-extension-installer "https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer"
chmod +x gnome-shell-extension-installer
sudo mv gnome-shell-extension-installer /usr/bin/


# install shell extensions
gnome-shell-extension-installer --yes 779
gnome-shell-extension-installer --yes 906

# refresh gnome-shell to find extensions
killall gnome-shell

# configure sound device shell extension: "sound-output-device-chooser@kgshank.net"
gnome-extensions enable sound-output-device-chooser@kgshank.net

# configure clipboard indicator shell extension: "clipboard-indicator@tudmotu.com"
gnome-extensions enable clipboard-indicator@tudmotu.com
dconf write "/org/gnome/shell/extensions/clipboard-indicator/cache-size" "2048"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/confirm-clear" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/disable-down-arrow" "true"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/display-mode" "0"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/enable-keybindings" "true"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/history-size" "99"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/move-item-first" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/notify-on-copy" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/preview-size" "99"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/refresh-interval" "500"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/strip-text" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/toggle-menu" "['<Control>Insert']"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/topbar-preview-size" "99"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/next-entry" "['<Control><Super>Right']"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/prev-entry" "['<Control><Super>Left']"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/clear-history" "['<Shift><Control>Delete']"

# configure bottom autohide dock
gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false
gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM
gsettings set org.gnome.shell.extensions.dash-to-dock show-mounts false
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
gsettings set org.gnome.shell.extensions.dash-to-dock autohide true
gsettings set org.gnome.shell.extensions.dash-to-dock intellihide true

# set light ubuntu color theme
gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-light'

# download and set wallpapers
# sudo curl -o /usr/share/backgrounds/fox-grey.jpg https://assets.hongkiat.com/uploads/minimalist-dekstop-wallpapers/non-4k/preview/06.jpg
# sudo curl -o /usr/share/backgrounds/starwars-yellow.jpg https://images.wallpapersden.com/image/download/r2-d2-star-wars-minimalist_a2xuaWWUmZqaraWkpJRqZWVlrWdqZWU.jpg
# sudo curl -o /usr/share/backgrounds/starwars-orange.jpg https://wallpaperboat.com/wp-content/uploads/2019/05/star-wars-minimalist-065.jpg
# sudo curl -o /usr/share/backgrounds/starwars-green.jpg https://images.wallpapersden.com/image/download/star-wars-skywalker-saga-minimal_a2xsbmqUmZqaraWkpJRnamtlrWZpaWU.jpg
# sudo curl -o /usr/share/backgrounds/city-green.jpg https://wallpaperboat.com/wp-content/uploads/2019/06/minimalist-desktop-17.jpg
# sudo curl -o /usr/share/backgrounds/desert-orange.jpg https://wallpaperbat.com/img/349312-minimalist-desert-wallpaper-for-desktop-1440p.jpg
sudo curl -o /usr/share/backgrounds/starwars-blue.jpg https://i1.wp.com/wallpapercave.com/wp/wp6722869.jpg

gsettings set org.gnome.desktop.screensaver picture-uri 'file:///usr/share/backgrounds/starwars-blue.jpg'
gsettings set com.ubuntu.login-screen background-picture-uri 'file:///usr/share/backgrounds/starwars-blue.jpg'
gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/starwars-blue.jpg'
