#!/usr/bin/env bash

if ! type "zsh" > /dev/null; then
  sudo DEBIAN_FRONTEND=noninteractive apt install -y zsh autojump
  sudo chsh -s $(which zsh) $(whoami)
  curl -L git.io/antigen > ~/.config/antigen.zsh
fi