#!/usr/bin/env bash

if ! type "zsh" > /dev/null; then
  . $DOTSPATH/lib/apt_install
  apt_install zsh autojump

  sudo chsh -s $(which zsh) $(whoami)
  curl -L git.io/antigen > ~/.config/antigen.zsh
fi

. $DOTSPATH/lib/link_file
link_dotfile .zshrc
link_dotfile .aliases
