#!/usr/bin/env bash


if ! type "java" > /dev/null; then
  wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
  sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
  sudo apt update

  sudo apt install adoptopenjdk-8-hotspot
fi