#!/usr/bin/env bash

if ! type "docker" > /dev/null; then
  # reference: https://docs.docker.com/engine/install/ubuntu/

  sudo DEBIAN_FRONTEND=noninteractive apt install -y \
      apt-transport-https \
      ca-certificates \
      gnupg \
      lsb-release

  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  # for ubuntu jammy docker repository is not yet available
  RELEASE=$(lsb_release -cs)
  if [ "$RELEASE" == "jammy" ]; then
    RELEASE="impish"
  fi

  echo \
      "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $RELEASE stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  sudo apt update
  sudo DEBIAN_FRONTEND=noninteractive apt install -y docker-ce docker-ce-cli containerd.io

  sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose

  sudo usermod -aG docker ${USER}
fi
