#!/bin/bash

if ! type "google-chrome" > /dev/null; then
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  sudo dpkg -i google-chrome-stable_current_amd64.deb

  rm google-chrome-stable_current_amd64.deb
fi