#!/bin/bash

if ! type "forticlient" > /dev/null; then
  wget -O - https://repo.fortinet.com/repo/6.4/ubuntu/DEB-GPG-KEY | sudo apt-key add -
  sudo bash -c "echo 'deb [arch=amd64] https://repo.fortinet.com/repo/6.4/ubuntu/ /bionic multiverse' >> /etc/apt/sources.list"
  sudo apt-get update
  sudo apt install forticlient
fi