#!/usr/bin/env bash
set -e

# increase keyboard speed
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 10
gsettings set org.gnome.desktop.peripherals.keyboard delay 240
gsettings set org.gnome.desktop.interface enable-hot-corners false
gsettings set org.gnome.desktop.interface enable-animations false
gio mime "inode/directory" org.gnome.Nautilus.desktop

# install gnome extensions
if ! type "gext" > /dev/null; then
  pipx install gnome-extensions-cli --system-site-packages
  pipx ensurepath
fi
export PATH="$HOME/.local/bin:$PATH"

gext install clipboard-indicator@tudmotu.com 2>/dev/null || true
gext enable clipboard-indicator@tudmotu.com
dconf write "/org/gnome/shell/extensions/clipboard-indicator/cache-size" "2048"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/confirm-clear" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/disable-down-arrow" "true"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/display-mode" "0"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/enable-keybindings" "true"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/history-size" "99"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/move-item-first" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/notify-on-copy" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/preview-size" "99"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/refresh-interval" "500"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/strip-text" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/toggle-menu" "['<Control>Insert']"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/topbar-preview-size" "99"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/next-entry" "['<Control><Super>Right']"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/prev-entry" "['<Control><Super>Left']"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/clear-history" "['<Shift><Control>Delete']"

# download and set wallpaper
WALLPAPER='/usr/share/backgrounds/starwars-green.jpg'
[ ! -f "$WALLPAPER" ] && sudo curl -fsSLo "$WALLPAPER" 'https://images.wallpapersden.com/image/download/star-wars-skywalker-saga-minimal_a2xsbmqUmZqaraWkpJRnamtlrWZpaWU.jpg'
gsettings set org.gnome.desktop.background picture-uri "file://$WALLPAPER"
gsettings set org.gnome.desktop.background picture-uri-dark "file://$WALLPAPER"
