#!/usr/bin/env bash
set -e

# keyboard layout: Italian (US)
gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'it+us')]"
gsettings set org.gnome.desktop.input-sources mru-sources "[('xkb', 'it+us')]"

# increase keyboard speed
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 10
gsettings set org.gnome.desktop.peripherals.keyboard delay 240
gsettings set org.gnome.desktop.interface enable-hot-corners false
gsettings set org.gnome.desktop.interface enable-animations false
gio mime "inode/directory" org.gnome.Nautilus.desktop

# free super+alt+arrow_up/down for ghostty goto_split (was: shift-overview)
gsettings set org.gnome.shell.keybindings shift-overview-up "[]"
gsettings set org.gnome.shell.keybindings shift-overview-down "[]"

# install gnome extensions cli
yay -S --needed --noconfirm gnome-extensions-cli

gext install clipboard-indicator@tudmotu.com 2>/dev/null || true
gext enable clipboard-indicator@tudmotu.com
dconf write "/org/gnome/shell/extensions/clipboard-indicator/cache-size" "2048"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/confirm-clear" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/disable-down-arrow" "true"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/display-mode" "0"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/enable-keybindings" "true"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/history-size" "99"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/move-item-first" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/notify-on-copy" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/preview-size" "99"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/refresh-interval" "500"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/strip-text" "false"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/toggle-menu" "['<Control>Insert']"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/topbar-preview-size" "99"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/next-entry" "['<Control><Alt>Right']"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/prev-entry" "['<Control><Alt>Left']"
dconf write "/org/gnome/shell/extensions/clipboard-indicator/clear-history" "['<Shift><Control>Delete']"

# download and set wallpaper
WALLPAPER='/usr/share/backgrounds/starwars-blue.jpg'
[ ! -f "$WALLPAPER" ] && sudo curl -fsSLo "$WALLPAPER" 'https://i1.wp.com/wallpapercave.com/wp/wp6722869.jpg'
gsettings set org.gnome.desktop.background picture-uri "file://$WALLPAPER"
gsettings set org.gnome.desktop.background picture-uri-dark "file://$WALLPAPER"
