#!/usr/bin/env bash

. $DOTSPATH/lib/link_file

yay -S --needed --noconfirm ghostty
link_file "$DOTSPATH/.config/ghostty/config" "$HOME/.config/ghostty/config"
gsettings set org.gnome.desktop.default-applications.terminal exec /usr/bin/ghostty
